version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: apple-music-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=apple_music
    networks:
      - apple-network

volumes:
  mongodb_data:
    driver: local

networks:
  apple-network:
    driver: bridge
